$font = Monospace

general {
    hide_cursor = false
    fail_timeout = 1000 # in milliseconds
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    # Fast, snappy bezier curve (accelerates quickly)
    bezier = snappy, 0.05, 0.9, 0.1, 1.05

    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldDots, 1, 2, linear
    animation = inputFieldColors, 1, 0.3, snappy
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
}

input-field {
    monitor =
    size = 20%, 4%
    outline_thickness = 0
    inner_color = rgba(0, 0, 0, 0.2)
    check_color = rgba(0, 0, 0, 0.4)
    fail_color = rgba(0, 0, 0, 0.2) rgba(0, 0, 0, 0.6)
    capslock_color = rgba(80, 0, 0, 0.2)

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 50

    font_family = $font
    placeholder_text = Enter password...
    fail_text = Try again

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = Hello, $USER
    font_size = 14
    font_family = $font

    position = 0, 35
    halign = center
    valign = center
}

label {
    monitor =
    text = $PAMFAIL
    font_size = 12
    font_family = $font
    color = rgba(200, 0, 0, 0.8)
    position = 0, -65
}

# TIME
label {
    monitor =
    text = <b>$TIME</b> # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 130
    font_family = $font

    position = -30, -100
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -80
    halign = center
    valign = top
}
